color: blue
fieldLayouts:
  bc4a3964-e809-4fb2-879a-7c10f42e628a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-23T02:05:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ae5c10f1-dc83-4e66-bcda-81a989cd2110
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-23T02:09:24+00:00'
            elementCondition: null
            fieldUid: 2db746d3-58af-43ef-8a84-d32b282b3e82 # Item
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97790231-f908-4849-9a4e-335d4b223668
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d079a896-74e1-44d1-8790-86bff389010a
        userCondition: null
handle: menuSection
hasTitleField: true
icon: pot-food
name: 'Menu Section'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
