baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'West Street Mini-Mart'
primary: true
siteGroup: b775f620-e1ac-4e5e-af04-d5e30236f06f # West Street Mini-Mart
sortOrder: 1
