altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  dbbedaa7-e25a-4ca6-8f11-a23383faef96:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-25T17:28:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c08f3943-bc17-49c9-b98e-4a3672fd2116
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 834f6b7d-0efa-4565-8bd7-db50d24850a3
        userCondition: null
fs: assets
handle: siteImages
name: 'Site Images'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
