dateModified: 1729641279
email:
  fromEmail: fultonchain@gmail.com
  fromName: 'West Street Mini-Mart'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    024375ab-589c-4361-9f22-e4d75204d0ec: 'West Street Mini-Mart' # West Street Mini-Mart
    b775f620-e1ac-4e5e-af04-d5e30236f06f: 'West Street Mini-Mart' # West Street Mini-Mart
system:
  edition: solo
  live: true
  name: 'West Street Mini-Mart'
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
