dateModified: 1731006600
email:
  fromEmail: fultonchain@gmail.com
  fromName: 'West Street Mini-Mart'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: Assets
    settings:
      path: /var/www/html/web/assets/images
    type: craft\fs\Local
    url: '@web/assets/images'
meta:
  __names__:
    1a4d943a-19e1-4852-bb5f-6dbc77b4fc34: 'Price (large)' # Price (large)
    1ea7a8d5-2482-496a-803d-cea497e4dd0b: About # About
    2db746d3-58af-43ef-8a84-d32b282b3e82: Item # Item
    3c62e9ed-f72f-46bd-a90e-2e288b57db39: Item # Item
    3d421dba-c01e-40a2-b9ad-4c39a95c3063: 'Site Images' # Site Images
    4a5855d5-11b9-49d6-bac2-6f11f9e02b3a: Subtitle # Subtitle
    5e0e970b-b2b5-4182-a31d-86cdc6ac5ab4: Menu # Menu
    7aaad26b-fd73-4038-a3e5-53b41b6683a9: 'Menu Section' # Menu Section
    14c30556-d0d6-401d-bdf3-ca19441e5ef9: 'Price (small)' # Price (small)
    43d913df-7e6a-4100-9dd0-29f41e1afdea: Text # Text
    179d9939-a1e1-460b-9ac7-8fd44d18526b: Text # Text
    6741bbf4-20a9-4560-9433-5f762a35f40f: Item # Item
    024375ab-589c-4361-9f22-e4d75204d0ec: 'West Street Mini-Mart' # West Street Mini-Mart
    10521530-c3bb-40eb-90cf-481562cb8a77: 'Raw HTML' # Raw HTML
    b3f00ec9-eea3-41c8-81f7-d7aa37becb9d: 'Menu Index' # Menu Index
    b775f620-e1ac-4e5e-af04-d5e30236f06f: 'West Street Mini-Mart' # West Street Mini-Mart
    beda8b67-3d1e-4408-849c-974d403a3ebc: Subtitle # Subtitle
    d80d45f3-c48d-45be-ae7c-46433ddba0e9: 'Contact Us' # Contact Us
    da258016-b548-44a9-8611-155fb882a5ae: 'Home Page' # Home Page
    ed9eaa32-adc4-4f85-9ca2-15791f283ed9: Simple # Simple
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
    settings:
      description: 'Welcome to West Street Mini Market, your neighborhood go-to spot for deli sandwiches, gyro and more. Located at 1601 West St. in Utica, NY 13501, we serve the Mohawk Valley and Central New York with Halal food.'
      facebookAppId: ''
      metaTemplate: ''
      removeAlternateUrls: ''
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\r\n\r\n{# Disallows #}\r\n{% if craft.app.config.env != 'production' %}\r\n\r\n{# Disallow access to everything when NOT in production #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage:
        - '234'
      title:
        -
          __assoc__:
            -
              - key
              - '1'
            -
              - locked
              - '0'
            -
              - template
              - '{title}'
        -
          __assoc__:
            -
              - key
              - '2'
            -
              - locked
              - '1'
            -
              - template
              - ' - {{ siteName }}'
      titleSuffix: null
      twitterHandle: ''
system:
  edition: solo
  live: true
  name: 'West Street Mini-Mart'
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
