defaultPlacement: end
enableVersioning: true
entryTypes:
  - 179d9939-a1e1-460b-9ac7-8fd44d18526b # Text
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  024375ab-589c-4361-9f22-e4d75204d0ec: # West Street Mini-Mart
    enabledByDefault: true
    hasUrls: true
    template: contact.twig
    uriFormat: contact
type: single
